urls:
  cognito: https://five-poc-globallogic.auth.us-east-1.amazoncognito.com  # cognito root auth url
endpoints:
  authorize: ${urls.cognito}/oauth2/authorize?response_type=code&client_id=${cognito.client}&redirect_uri=${cognito.callback}
  token: ${urls.cognito}/oauth2/token
cognito:
  client: "7bn0bcd3s61aob1qpqb4e7sdh8"    # cognito client id
  secret: "1kv6o7j5u561qiu258v5907q1u8in3pv10k06fj1ij4vsn9dkt51"     # cognito client secret
  callback: http://localhost:8080/auth/token  # valid callback url set in cognito
  region: us-east-1 # Cognito's aws region
  userPoolId: us-east-1_Qa9A6gY0T # Cognito's User Pool Id
  keys: https://cognito-idp.${cognito.region}.amazonaws.com/${cognito.userPoolId}/.well-known/jwks.json # url for cognito jwt keys